/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.app.demo.repository;

import java.util.Date;
import javax.inject.Named;
import javax.inject.Singleton;
import com.app.demo.domain.Civility;
import com.app.demo.domain.Person;
import com.app.demo.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class PersonGenerator {

    /**
     * Returns a new Person instance filled with random values.
     */
    public Person getPerson() {
        Person person = new Person();

        // simple attributes follows
        person.setUsername(ValueGenerator.getUniqueString(255));
        person.setPassword("a");
        person.setEmail(ValueGenerator.getUniqueEmail());
        person.setIsEnabled(true);
        person.setCivility(Civility.MR);
        person.setFirstName("a");
        person.setLastName("a");
        person.setBirthDate(new Date());
        person.setPhoto("d");
        return person;
    }

}