/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/RepositoryTest.e.vm.java
 */
package com.app.demo.repository;

import static org.fest.assertions.Assertions.assertThat;
import static org.mockito.Matchers.any;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.runners.MockitoJUnitRunner;

import com.app.demo.domain.Person;
import com.app.demo.repository.PersonRepository;
import com.app.demo.dao.PersonDao;
import com.app.demo.domain.Civility;
import com.app.demo.dao.support.SearchParameters;

/**
 * Unit test on PersonRepository
 */
@RunWith(MockitoJUnitRunner.class)
public class PersonRepositoryTest {

    @Mock
    private PersonDao personDao;

    @InjectMocks
    private PersonRepository personRepository;

    @Test
    public void findUniqueOrNoneReturnsNull() {
        when(personDao.findUniqueOrNone(any(Person.class), any(SearchParameters.class))).thenReturn(null);

        Person result = personRepository.findUniqueOrNone(new Person());

        assertThat(result).isNull();
        verify(personDao, times(1)).findUniqueOrNone(any(Person.class), any(SearchParameters.class));
    }

    @Test
    public void findUniqueOrNoneReturnsSingleValue() {
        Person unique = new Person();

        when(personDao.findUniqueOrNone(any(Person.class), any(SearchParameters.class))).thenReturn(unique);

        Person result = personRepository.findUniqueOrNone(new Person());

        assertThat(result).isNotNull().isSameAs(unique);
        verify(personDao, times(1)).findUniqueOrNone(any(Person.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void findUniqueOrNoneThrowsExceptionWhenNonUniqueResults() {
        when(personDao.findUniqueOrNone(any(Person.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        personRepository.findUniqueOrNone(new Person());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void findUniqueThrowsExceptionWhenNoResult() {
        when(personDao.findUnique(any(Person.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        personRepository.findUnique(new Person());
    }

    @Test
    public void findUnique() {
        Person unique = new Person();

        when(personDao.findUnique(any(Person.class), any(SearchParameters.class))).thenReturn(unique);

        Person result = personRepository.findUnique(new Person());

        assertThat(result).isNotNull();
        verify(personDao, times(1)).findUnique(any(Person.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void findUniqueThrowsExeptionWhenNonUniqueResult() {
        when(personDao.findUnique(any(Person.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        personRepository.findUnique(new Person());
    }
}