/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces-sd:src/main/java/MessageBundle.p.vm.java
 */
package com.app.demo.web.util;

import java.util.Enumeration;
import java.util.ResourceBundle;

import com.app.demo.util.ResourcesUtil;

/**
 * This ResourceBundle is set in faces-config.xml under 'msg' var.
 * Implementation uses Spring MessageSource.
 * From your JSF2 pages, you may use #{msg.property_key} 
 */
public class MessageBundle extends ResourceBundle {

	private ResourcesUtil resourcesUtil;

    @Override
    public Enumeration<String> getKeys() {
        return null;
    }

    @Override
    protected Object handleGetObject(String key) {
        if (resourcesUtil == null) {
            resourcesUtil = ResourcesUtil.getInstance();
        }
        return resourcesUtil.getProperty(key);
    }
}