/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/dao/DAOImpl.e.vm.java
 */
package com.app.demo.dao;

import static com.app.demo.domain.Person_.email;
import static com.app.demo.domain.Person_.firstName;
import static com.app.demo.domain.Person_.lastName;
import static com.app.demo.domain.Person_.username;
import javax.inject.Named;
import javax.inject.Singleton;
import com.app.demo.dao.PersonDao;
import com.app.demo.dao.support.GenericDao;
import com.app.demo.domain.Person;

/**
 * JPA 2 Data Access Object for {@link Person}.
 * Note: do not use @Transactional in the DAO layer.
 */
@Named
@Singleton
public class PersonDao extends GenericDao<Person, String> {
    public PersonDao() {
        super(Person.class, username, email, firstName, lastName);
    }
}