/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/hibernate/DAOHibernate.e.vm.java
 */
package com.app.demo.dao;

import org.hibernate.Criteria;
import org.springframework.stereotype.Repository;
import com.app.demo.dao.PersonDao;
import com.app.demo.dao.hibernate.HibernateUtil;
import com.app.demo.dao.support.SearchTemplate;
import com.app.demo.domain.Person;

import com.app.demo.dao.hibernate.HibernateGenericDao;

/**
 * Hibernate implementation of the {@link PersonDao} interface.
 */
@Repository
public class PersonDaoImpl extends HibernateGenericDao<Person, String> implements PersonDao {
    public PersonDaoImpl() {
        super(Person.class);
    }

    /**
     * Constructs the search by example criteria using not only the passed {@link Person} but also its associated entities.
     */
    @Override
    public Criteria getCriteria(Person person, SearchTemplate searchTemplate) {
        // Call super to construct the criteria of the 'root' entity.
        Criteria criteria = super.getCriteria(person, searchTemplate);
        HibernateUtil.applyToManyAssociationOnCriteria(criteria, searchTemplate, "roles", person.getRoles());
        return criteria;
    }
}