/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/dao/DAO.e.vm.java
 */
package com.app.demo.dao;

import com.app.demo.dao.support.GenericDao;
import com.app.demo.domain.Role;

/**
 * DAO Interface for {@link Role}
 */
public interface RoleDao extends GenericDao<Role, Integer> {
}
