/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/manager/ModelGenerator.e.vm.java
 */
package com.app.demo.service;

import java.util.Date;
import org.springframework.stereotype.Service;
import com.app.demo.domain.Person;
import com.app.demo.domain.enums.CivilityEnum;
import com.app.demo.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Service
public class PersonGenerator {

    /**
     * Returns a new Person instance filled with random values.
     */
    public Person getPerson() {
        Person person = new Person();

        // simple attributes follows
        person.setUsername(ValueGenerator.getUniqueString(255));
        person.setPassword("a");
        person.setEmail(ValueGenerator.getUniqueEmail());
        person.setIsEnabled(true);
        person.setCivility(CivilityEnum.MR);
        person.setFirstName("a");
        person.setLastName("a");
        person.setBirthDate(new Date());
        return person;
    }

}