/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/hibernate/DAOHibernateWithRealSessionTest.e.vm.java
 */
package com.app.demo.dao;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.app.demo.domain.Person;
import com.app.demo.service.PersonGenerator;
import com.app.demo.dao.PersonDao;
import com.app.demo.util.*;

/**
 * Integration test on PersonDaoImpl
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class PersonDaoImplWithRealSessionTest {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(PersonDaoImplWithRealSessionTest.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Autowired
    private PersonDao personDao;

    @Autowired
    private PersonGenerator personGenerator;

    @Before
    public void onSetUp() throws Exception {
    }

    @Test
    public void testSaveAndGet() {
        Person person = personGenerator.getPerson();

        // add it to a Set before saving (force equals/hashcode)
        Set<Person> set = new HashSet<Person>();
        set.add(person);

        personDao.save(person);
        entityManager.flush();

        // reload it from cache and check equality
        Person model = new Person();
        model.setId(person.getId());
        assertThat(person).isEqualTo(personDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // since you use a business key, equality must be preserved.
        assertThat(person).isEqualTo(personDao.get(model));
    }
}