/*
SQLyog Ultimate v8.55 
MySQL - 5.5.16-log : Database - app
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`app` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `app`;

/*Table structure for table `person` */

DROP TABLE IF EXISTS `person`;

CREATE TABLE `person` (
  `ID` varchar(32) NOT NULL,
  `LOGIN` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `IS_ENABLED` tinyint(1) DEFAULT NULL,
  `CIVILITY` varchar(2) DEFAULT NULL,
  `FIRST_NAME` varchar(255) DEFAULT NULL,
  `LAST_NAME` varchar(255) DEFAULT NULL,
  `BIRTH_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `VERSION` int(10) DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PERSON_UNIQUE_1_INDEX_8` (`LOGIN`),
  UNIQUE KEY `PERSON_UNIQUE_2_INDEX_8` (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `person_role` */

DROP TABLE IF EXISTS `person_role`;

CREATE TABLE `person_role` (
  `PERSON_ID` varchar(32) NOT NULL,
  `ROLE_ID` int(10) NOT NULL,
  PRIMARY KEY (`PERSON_ID`,`ROLE_ID`),
  KEY `PERSON_ROLE_FK_1_INDEX_6` (`PERSON_ID`),
  KEY `PERSON_ROLE_FK_2_INDEX_6` (`ROLE_ID`),
  CONSTRAINT `PERSON_ROLE_FK_1` FOREIGN KEY (`PERSON_ID`) REFERENCES `person` (`ID`),
  CONSTRAINT `PERSON_ROLE_FK_2` FOREIGN KEY (`ROLE_ID`) REFERENCES `role` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `role` */

DROP TABLE IF EXISTS `role`;

CREATE TABLE `role` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` varchar(255) NOT NULL,
  `ROLE_DESC` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ROLE_UNIQUE_1_INDEX_2` (`ROLE_NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
