/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/EntityMeta_.e.vm.java
 */
package com.app.demo.domain;

import java.util.Date;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import com.app.demo.domain.Civility;
import com.app.demo.domain.Role;

@StaticMetamodel(Person.class)
public abstract class Person_ {

    // Raw attributes
    public static volatile SingularAttribute<Person, String> id;
    public static volatile SingularAttribute<Person, String> username;
    public static volatile SingularAttribute<Person, String> password;
    public static volatile SingularAttribute<Person, String> email;
    public static volatile SingularAttribute<Person, Boolean> isEnabled;
    public static volatile SingularAttribute<Person, Civility> civility;
    public static volatile SingularAttribute<Person, String> firstName;
    public static volatile SingularAttribute<Person, String> lastName;
    public static volatile SingularAttribute<Person, Date> birthDate;
    public static volatile SingularAttribute<Person, Integer> version;
    public static volatile SingularAttribute<Person, String> photo;

    // Many to many
    public static volatile ListAttribute<Person, Role> securityRoles;
}